---
- hosts: localhost
  connection: local
  
  vars_files:
    - vars/main.yml
  
  roles:
    - { name: homebrew, when: ansible_distribution == "MacOSX" }
    - { name: zsh, tags: [zsh] }
    - { name: geerlingguy.dotfiles, tags: [dotfiles] }
  tasks:
    - include: tasks/main.yml
