---

- name: Install Mac App Store apps with mas-cli
  shell: "scripts/mas_install.sh '{{ item }}'"
  args:
    creates: "/Applications/{{ item }}.app"
  with_items: "{{ mas_apps }}"
  tags:
    - mas
    - macos


- name: Configure the Dock
  block:
    - name: Disable showing recent files
      shell: "defaults write com.apple.dock show-recents -bool false"

    - name: Remove specified items from Dock
      shell: "dockutil --remove '{{ item }}'"
      ignore_errors: true
      with_items: "{{ dockitems_to_remove }}"


    - name: Check if items in dock exist
      shell: "dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'"
      with_items: "{{ dockitems_to_persist }}"


    - name: Fix order
      shell: "dockutil --move '{{ item.name }}' --position {{ item.pos }}"
      with_items: "{{ dockitems_to_persist }}"
  tags:
    - macos
    - dock


- name: Ensure standby mode behaves properly
  shell: "sudo pmset -a {{ item }}"
  with_items:
    - powernap 0
    - standby 0
    - standbydelayhigh 0
    - standbydelaylow 0
    - autopoweroff 0


- name: Include Fixes for Homebrew links and apps
  include: homebrew_fixes.yml
