---
- name: Install NPM Packages
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - "{{ npm_modules }}"
  tags:
    - npm

- name: Clone Git Repos
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items: "{{ git_repos }}"

- name: Install easy_install packages
  easy_install:
    name: ipython

- name: Install Python Packages
  pip:
    name: "{{ item.name }}"
    extra_args: "{{ item.extra_args | default(omit) }}"
    executable: "{{ item.executable | default('pip') }}"
  become: "{{ item.become | default('no') }}"
  with_items: "{{ python_packages }}"
  tags:
      - python

- name: Include macOS Tasks
  include: macos.yml
  when: ansible_os_family == "Darwin"
